// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc293.DeepestSpace;

import org.usfirst.frc293.DeepestSpace.commands.*;
import org.usfirst.frc293.DeepestSpace.commands.MoveElevator;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import org.usfirst.frc293.DeepestSpace.subsystems.*;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick leftJoy;
    public Joystick rightJoy;
    public JoystickButton openGripB;
    public JoystickButton gripCloseB;
    public JoystickButton shootB;
    public JoystickButton armUpB;
    public JoystickButton armDownB;
    public JoystickButton moveArmToVert;
    public JoystickButton moveArmToShoot;
    public JoystickButton moveArmToHoriz;
    public JoystickButton moveArmToFeed;
    public Joystick opLeftJoy;
    public JoystickButton moveElevLowHatch;
    public JoystickButton moveElevLowCargo;
    public JoystickButton moveElevMidHatch;
    public JoystickButton moveElevMidCargo;
    public JoystickButton moveElevHighHatch;
    public JoystickButton moveElevHighCargo;
    public JoystickButton moveTopUpB;
    public JoystickButton moveBottomUpB;
    public JoystickButton moveTopDownB;
    public JoystickButton moveBottomDownB;
    public Joystick opRightJoy;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        opRightJoy = new Joystick(2);
        
        moveBottomDownB = new JoystickButton(opRightJoy, 4);
        moveBottomDownB.whileHeld(new MoveBottomDown());
        moveTopDownB = new JoystickButton(opRightJoy, 3);
        moveTopDownB.whileHeld(new MoveTopDown());
        moveBottomUpB = new JoystickButton(opRightJoy, 6);
        moveBottomUpB.whileHeld(new MoveBottomUp());
        moveTopUpB = new JoystickButton(opRightJoy, 5);
        moveTopUpB.whileHeld(new MoveTopUp());
        moveElevHighCargo = new JoystickButton(opRightJoy, 11);
        moveElevHighCargo.whenPressed(new MoveElevator(""));
        moveElevHighHatch = new JoystickButton(opRightJoy, 12);
        moveElevHighHatch.whenPressed(new MoveElevator(""));
        moveElevMidCargo = new JoystickButton(opRightJoy, 9);
        moveElevMidCargo.whenPressed(new MoveElevator(""));
        moveElevMidHatch = new JoystickButton(opRightJoy, 10);
        moveElevMidHatch.whenPressed(new MoveElevator(""));
        moveElevLowCargo = new JoystickButton(opRightJoy, 7);
        moveElevLowCargo.whenPressed(new MoveElevator("LowCargo"));
        moveElevLowHatch = new JoystickButton(opRightJoy, 8);
        moveElevLowHatch.whenPressed(new MoveElevator("LowHatch"));
        opLeftJoy = new Joystick(3);
        
        moveArmToFeed = new JoystickButton(opLeftJoy, 11);
        moveArmToFeed.whenPressed(new ArmToAngle(100));
        moveArmToHoriz = new JoystickButton(opLeftJoy, 9);
        moveArmToHoriz.whenPressed(new ArmToAngle(90));
        moveArmToShoot = new JoystickButton(opLeftJoy, 10);
        moveArmToShoot.whenPressed(new ArmToAngle(60));
        moveArmToVert = new JoystickButton(opLeftJoy, 7);
        moveArmToVert.whenPressed(new ArmToAngle(0));
        armDownB = new JoystickButton(opLeftJoy, 4);
        armDownB.whileHeld(new ArmDown());
        armUpB = new JoystickButton(opLeftJoy, 6);
        armUpB.whileHeld(new ArmUp());
        shootB = new JoystickButton(opLeftJoy, 1);
        shootB.whenPressed(new Shoot());
        gripCloseB = new JoystickButton(opLeftJoy, 3);
        gripCloseB.whenPressed(new GripClose());
        openGripB = new JoystickButton(opLeftJoy, 5);
        openGripB.whenPressed(new GripOpen());
        rightJoy = new Joystick(0);
        
        leftJoy = new Joystick(1);
        


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("DriveWJoystick", new DriveWJoystick());
        SmartDashboard.putData("GripOpen", new GripOpen());
        SmartDashboard.putData("GripClose", new GripClose());
        SmartDashboard.putData("PusherIn", new PusherIn());
        SmartDashboard.putData("PusherOut", new PusherOut());
        SmartDashboard.putData("BackStiltsUp", new BackStiltsUp());
        SmartDashboard.putData("BackStiltsDown", new BackStiltsDown());
        SmartDashboard.putData("FrontStiltsUp", new FrontStiltsUp());
        SmartDashboard.putData("FrontStiltsDown", new FrontStiltsDown());
        SmartDashboard.putData("ClimberForward", new ClimberForward());
        SmartDashboard.putData("DownUntilLimit", new DownUntilLimit());
        SmartDashboard.putData("MoveElevator", new MoveElevator("string"));
        SmartDashboard.putData("DriveForward", new DriveForward());
        SmartDashboard.putData("ArmToAngle", new ArmToAngle(0));
        SmartDashboard.putData("Shoot", new Shoot());
        SmartDashboard.putData("MoveTopUp", new MoveTopUp());
        SmartDashboard.putData("MoveTopDown", new MoveTopDown());
        SmartDashboard.putData("MoveBottomUp", new MoveBottomUp());
        SmartDashboard.putData("MoveBottomDown", new MoveBottomDown());
        SmartDashboard.putData("ArmUp", new ArmUp());
        SmartDashboard.putData("ArmDown", new ArmDown());
        SmartDashboard.putData("ArmUpUntilLimit", new ArmUpUntilLimit());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        shootB.whenReleased(new PusherIn());
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getLeftJoy() {
        return leftJoy;
    }

    public Joystick getRightJoy() {
        return rightJoy;
    }

    public Joystick getOpLeftJoy() {
        return opLeftJoy;
    }

    public Joystick getOpRightJoy() {
        return opRightJoy;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    
}

